apiVersion: '2018-10-01'
location: westus
name: pu-smas-postgres
properties:
  osType: Linux
  imageRegistryCredentials:
  - server: pusmascg.azurecr.io
    username: pusmascg
    password: zgQ8GAbC6J4QTSO/Z4C9OYRqhWvZeVkKn+JCe3ANoY+ACRBDfiOX
  containers:
  - name: pu-smas-postgres
    properties:
      image: pusmascg.azurecr.io/pu_smas_postgres
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      ports:
      - port: 5432
      environmentVariables:
      - name: POSTGRES_USER
        value: pu_smas_user
      - name: POSTGRES_PASSWORD
        value: pu_smas_password@@!
      - name: POSTGRES_DB
        value: pu_smas_postgres
  restartPolicy: Always
  ipAddress:
    ports:
    - protocol: tcp
      port: '5432'
    type: Public
tags: null
type: Microsoft.ContainerInstance/containerGroups